spring: 
  profiles:
    active: prd
  mvc:
    view:
      prefix: /templates/
      suffix: .html
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # MyBatis配置文件所在路径
  type-aliases-package: com.dee.xql.api.model         # 定义所有操作类的别名所在包
  mapper-locations:                                   # 定义所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
